#################################
# Dependabot Configuration File #
#################################

# current Github-native version of Dependabot
version: 2

updates:
  # Enable version updates for Python libs in Openverse API
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/openverse_api` directory
    directory: /openverse_api
    # Check for updates once a week
    schedule:
      interval: monthly
    labels:
      - "💻 aspect: code"
      - "🧰 goal: internal improvement"
      - "🟩 priority: low"
      - dependencies
      - python

  # Enable version updates for Python libs in ingestion server
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/ingestion_server` directory
    directory: /ingestion_server
    # Check for updates once a week
    schedule:
      interval: monthly
    labels:
      - "💻 aspect: code"
      - "🧰 goal: internal improvement"
      - "🟩 priority: low"
      - dependencies
      - python

  # Enable version updates for Python libs in analytics
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/analytics` directory
    directory: /analytics
    # Check for updates once a week
    schedule:
      interval: monthly
    labels:
      - "💻 aspect: code"
      - "🧰 goal: internal improvement"
      - "🟩 priority: low"
      - dependencies
      - python
