# Generated by Django 3.2.9 on 2022-02-14 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_singular_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('audio_identifier', models.UUIDField(db_index=True, help_text='The identifier of the audio object.', unique=True)),
                ('waveform_peaks', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='The waveform peaks. A list of floats in the range of 0 -> 1 inclusively.', null=True, size=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
