# Generated by Django 4.0.3 on 2022-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_throttledapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='test_field',
            field=models.TextField(default=''),
        ),
    ]
