# Generated by Django 4.0.6 on 2022-07-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_migrations_number_48'),
    ]

    operations = [
    ]
