# Generated by Django 4.1.2 on 2022-12-12 05:54

from django.db import migrations, models
import django.db.models.deletion


REPORTING_TABLES = [
    "api_deletedaudio",
    "api_deletedimage",
    "api_matureaudio",
    "api_matureimage",
    "nsfw_reports",
    "nsfw_reports_audio",
]
forward_query = "".join([
    f"UPDATE {table} SET media_obj_id = identifier;"
    for table in REPORTING_TABLES
])
reverse_query = "".join([
    f"UPDATE {table} SET identifier = media_obj_id;"
    for table in REPORTING_TABLES
])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_delete_sourcelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedimage',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matureimage',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedaudio',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matureaudio',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagereport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, null=True, related_name="image_report", help_text="The reference to the image being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, related_name="deleted_image", help_text="The reference to the deleted image.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matureimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, related_name="mature_image", help_text="The reference to the mature image.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioreport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, null=True, related_name="audio_report", help_text="The reference to the audio being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, related_name="deleted_audio", help_text="The reference to the deleted audio.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matureaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, related_name="mature_audio", help_text="The reference to the mature audio.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            forward_query,
            reverse_query,
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, related_name="image_report", help_text="The reference to the image being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, related_name="deleted_image", help_text="The reference to the deleted image.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='matureimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, related_name="mature_image", help_text="The reference to the mature image.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='audioreport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, related_name="audio_report", help_text="The reference to the audio being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, related_name="deleted_audio", help_text="The reference to the deleted audio.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='matureaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, related_name="mature_audio", help_text="The reference to the mature audio.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.RemoveField(
            model_name='imagereport',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='deletedimage',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='matureimage',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='audioreport',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='deletedaudio',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='matureaudio',
            name='identifier',
        ),
        migrations.AddField(
            model_name='audio',
            name='audioset',
            field=models.ForeignObject(from_fields=('audio_set_foreign_identifier', 'provider'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.audioset', to_fields=('foreign_identifier', 'provider')),
        ),
    ]
