# Generated by Django 4.1.2 on 2022-12-12 05:54

from django.db import migrations, models
import django.db.models.deletion


REPORTING_TABLES = [
    "api_deletedaudio",
    "api_deletedimage",
    "api_matureaudio",
    "api_matureimage",
    "nsfw_reports",
    "nsfw_reports_audio",
]
forward_query = "".join([
    f"UPDATE {table} SET media_obj_id = identifier;"
    for table in REPORTING_TABLES
])
reverse_query = "".join([
    f"UPDATE {table} SET identifier = media_obj_id;"
    for table in REPORTING_TABLES
])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_delete_sourcelogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagereport',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='audioreport',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='imagereport',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audioreport',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matureimage',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matureaudio',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deletedimage',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matureimage',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedaudio',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matureaudio',
            name='identifier',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagereport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, null=True, help_text="The foreign key to the 'Image' being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, help_text="The foreign key from this model to the 'Image' model.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matureimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, help_text="The foreign key from this model to the 'Image' model.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioreport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, null=True, help_text="The foreign key to the 'Audio' being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, help_text="The foreign key of this model to the 'Audio' model.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matureaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, null=True, help_text="The foreign key of this model to the 'Audio' model.", on_delete=django.db.models.deletion.DO_NOTHING, serialize=False, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            forward_query,
            reverse_query,
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, help_text="The foreign key to the 'Image' being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.image', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, help_text="The foreign key from this model to the 'Image' model.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='matureimage',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, help_text="The foreign key from this model to the 'Image' model.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='audioreport',
            name='media_obj',
            field=models.ForeignKey(db_constraint=False, help_text="The foreign key to the 'Audio' being reported.", on_delete=django.db.models.deletion.DO_NOTHING, to='api.audio', to_field='identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, help_text="The foreign key of this model to the 'Audio' model.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='matureaudio',
            name='media_obj',
            field=models.OneToOneField(db_constraint=False, help_text="The foreign key of this model to the 'Audio' model.", on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.RemoveField(
            model_name='imagereport',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='deletedimage',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='matureimage',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='audioreport',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='deletedaudio',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='matureaudio',
            name='identifier',
        ),
    ]
