# Generated by Django 4.1.4 on 2023-01-17 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_relational_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='The date the query was executed.')),
                ('query_hash', models.CharField(help_text='The query hash generated by ``dead_link_mask.get_query_hash``.', max_length=256)),
                ('query_params', models.JSONField(help_text='The query parameters used to execute the query.')),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), help_text='List of result IDs for the query.', size=None)),
                ('page', models.IntegerField(help_text='The page number of the request. Extracted from ``query_params`` for ease of querying.')),
            ],
        ),
    ]
