version: "2.4"
services:
  ingestion_server:
    image: openverse/ingestion_server:1.4.0
    ports:
      - "8001:8001"
    env_file:
      - .env
    dns:
      # Related to DNS management on the production box.
      # Not sure if this is strictly necessary, but it exists
      # in the current, running system so we are retaining it here.
      - 172.31.0.2
