name: Automated tests
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Lint
      working-directory: ./openverse_api
      run: |
        pip install pre-commit
        pre-commit run --all-files
  Tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: extractions/setup-just@v1
    - name: Install dependencies
      run: |
        pip install pytest pipenv
        sudo apt-get install libexempi8 librdkafka-dev
        PIPENV_PIPFILE=./openverse_api/Pipfile pipenv install --system --deploy --dev &
    - name: Pull containers
      run: docker-compose pull --ignore-pull-failures
    - name: Cache Docker images
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Start API, ingest and index test data
      run: just init
    - name: Wait for data to be indexed in Elasticsearch
      run: bash -c 'while [[ "$(curl -sb -H "Accept:application/json" http://localhost:9200/_cat/aliases/image | grep -c image-)" == "0" || "$(curl -sb -H "Accept:application/json" http://localhost:9200/_cat/aliases/audio | grep -c audio-)" == "0" ]]; do sleep 5 && docker-compose logs; done'
    - name: Run API tests
      working-directory: ./openverse_api
      env:
        PIPENV_DOTENV_LOCATION: ./env.template
      run: pipenv run test/run_test.sh
    - name: Run analytics tests
      working-directory: ./analytics
      run: docker exec -i openverse-api_analytics_1 /bin/bash -c 'PYTHONPATH=. pipenv run pytest tests.py'
