name: Automated tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Cache pre-commit envs
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit to lint files
        run: |
          pip install pre-commit
          pre-commit run --all-files

  test-ing:
    name: Run tests for ingestion-server
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup just
        uses: extractions/setup-just@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Install Python deps for ingestion-server
        run: |
          pip install -U pip
          pip install pipenv
          just _ing-install
      - name: Build image `ingestion_server`
        uses: docker/build-push-action@v2
        with:
          context: ./ingestion_server/
          push: false
          load: true
          tags: ingestion_server
          cache-from: type=gha,scope=ingestion_server
          cache-to: type=gha,scope=ingestion_server
      - name: Run ingestion-server tests
        run: just ing-testlocal

  test-api:
    name: Run tests for the API
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup just
        uses: extractions/setup-just@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build image `openverse_api`
        uses: docker/build-push-action@v2
        with:
          context: ./openverse_api/
          push: false
          load: true
          target: api
          tags: openverse_api
          cache-from: type=gha,scope=openverse_api
          cache-to: type=gha,scope=openverse_api,mode=max
      - name: Build image `ingestion_server`
        uses: docker/build-push-action@v2
        with:
          context: ./ingestion_server/
          push: false
          load: true
          tags: ingestion_server
          cache-from: type=gha,scope=ingestion_server
          cache-to: type=gha,scope=ingestion_server
      - name: Build image `indexer_worker`
        uses: docker/build-push-action@v2
        with:
          context: ./ingestion_server/
          file: ./ingestion_server/Dockerfile_worker
          push: false
          load: true
          tags: indexer_worker
          cache-from: type=gha,scope=indexer_worker
          cache-to: type=gha,scope=indexer_worker
      - name: Build image `analytics`
        uses: docker/build-push-action@v2
        with:
          context: ./analytics/
          push: false
          load: true
          tags: analytics
          cache-from: type=gha,scope=analytics
          cache-to: type=gha,scope=analytics
      - name: Start API, ingest and index test data
        run: just init
      - name: Run API tests
        run: just api-test -T
      - name: Run analytics tests
        run: just nl-test -T
