name: PR Closed

on:
  pull_request:
    types:
      - closed

jobs:
  clean-gh-pages:
    name: Clean API developer docs preview
    runs-on: ubuntu-latest
    # Check if the event is not triggered by a fork or dependabot
    if: github.event_name == 'pull_request' && github.repository_owner == 'WordPress' && github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Remove PR preview
        run: rm -rf _preview/${{ github.event.pull_request.number }}

      - name: Push cleaned branch
        run: |
          git config --global user.name 'PR Closed action'
          git config --global user.email 'openverse@wordpress.org'
          git commit -am 'Clean preview for PR ${{ github.event.pull_request.number }}'
          git push
