name: PR label check
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-label-check

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  check_aspect_label:
    name: Check aspect label
    runs-on: ubuntu-latest
    steps:
      - name: Check aspect label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "🚦 status: awaiting triage,💻 aspect: code,📄 aspect: text,🤖 aspect: dx,🕹 aspect: interface,♿️ aspect: a11y"

  check_goal_label:
    name: Check goal label
    runs-on: ubuntu-latest
    steps:
      - name: Check goal label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "🚦 status: awaiting triage,🌟 goal: addition,🛠 goal: fix,✨ goal: improvement,🧰 goal: internal improvement"

  check_priority_label:
    name: Check priority label
    runs-on: ubuntu-latest
    steps:
      - name: Check priority label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "🚦 status: awaiting triage,🟩 priority: low,🟨 priority: medium,🟧 priority: high,🟥 priority: critical"
