name: New PR notification
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#new-pr-notification

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

jobs:
  send_message:
    name: Send Slack message
    if: |
      github.actor != 'dependabot[bot]' &&
      !startsWith(github.event.pull_request.title, '🔄')
    runs-on: ubuntu-latest
    env:
      slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_author: ${{ github.event.pull_request.user.login }}
      pr_repo: ${{ github.event.pull_request.base.repo.full_name }}
    steps:
      - name: Send notification for new PR
        if: github.event.action == 'opened'
        env:
          pr_status: ${{ github.event.pull_request.draft && ' draft ' || ' ' }}
          pr_icon: ${{ github.event.pull_request.draft && ':pr-draft:' || ':pull-request:' }}
        run: |
          curl \
            $slack_url \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{"text":"New'"$pr_status"'PR opened by '"$pr_author"' in '"$pr_repo"': #'"$pr_number"' - '"$pr_title"'","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"'"$pr_icon"' New'"$pr_status"'PR opened by *'"$pr_author"'* in `'"$pr_repo"'`:\n<'"$pr_url"'|#'"$pr_number"' - '"$pr_title"'>"}}]}'

      - name: Send notification for PR marked ready
        if: github.event.action == 'ready_for_review'
        run: |
          curl \
            $slack_url \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{"text":"PR by '"$pr_author"' in '"$pr_repo"' marked ready for review: #'"$pr_number"' - '"$pr_title"'","blocks":[{"type":"section","text":{"type":"mrkdwn","text":":pull-request: PR by *'"$pr_author"'* in `'"$pr_repo"'` marked ready for review:\n<'"$pr_url"'|#'"$pr_number"' - '"$pr_title"'>"}}]}'
